# Generated by Django 4.2.5 on 2023-09-09 05:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wiki", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="notes",
            field=models.TextField(null=True),
        ),
        migrations.CreateModel(
            name="StandaloneExercise",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(null=True)),
                ("practice_notes", models.TextField(null=True)),
                ("order", models.IntegerField(null=True)),
                (
                    "book",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exercises",
                        to="wiki.book",
                    ),
                ),
                (
                    "composer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exercises",
                        to="wiki.composer",
                    ),
                ),
                (
                    "recording",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="wiki.recording",
                    ),
                ),
                ("skills", models.ManyToManyField(to="wiki.skill")),
            ],
        ),
    ]
