# Generated by Django 4.2.5 on 2023-09-09 05:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wiki", "0002_alter_book_notes_standaloneexercise"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="book",
            name="notes",
        ),
        migrations.AddField(
            model_name="book",
            name="description",
            field=models.TextField(null=True),
        ),
    ]
