# Generated by Django 4.2.5 on 2023-09-09 05:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wiki", "0003_remove_book_notes_book_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="piece",
            name="book",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="pieces",
                to="wiki.book",
            ),
        ),
        migrations.AlterField(
            model_name="piece",
            name="composer",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="pieces",
                to="wiki.composer",
            ),
        ),
        migrations.AlterField(
            model_name="piece",
            name="recording",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wiki.recording",
            ),
        ),
    ]
