# Generated by Django 4.2.5 on 2023-09-09 05:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wiki", "0004_alter_piece_book_alter_piece_composer_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="piece",
            name="book",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="pieces",
                to="wiki.book",
            ),
        ),
        migrations.AlterField(
            model_name="piece",
            name="composer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="pieces",
                to="wiki.composer",
            ),
        ),
        migrations.AlterField(
            model_name="piece",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="piece",
            name="order",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="piece",
            name="practice_notes",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="piece",
            name="recording",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wiki.recording",
            ),
        ),
        migrations.AlterField(
            model_name="pieceexercise",
            name="abc_notation",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="pieceexercise",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="skill",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="spot",
            name="abc_notation",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="spot",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="spot",
            name="order",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="spot",
            name="recording",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="wiki.recording",
            ),
        ),
        migrations.AlterField(
            model_name="spot",
            name="skills",
            field=models.ManyToManyField(blank=True, null=True, to="wiki.skill"),
        ),
        migrations.AlterField(
            model_name="step",
            name="recording",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="wiki.recording",
            ),
        ),
    ]
