# Generated by Django 4.2.5 on 2023-09-09 06:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wiki", "0006_alter_piece_large_sections_alter_piece_skills_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="spot",
            name="measures",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
