# Generated by Django 4.2.5 on 2023-09-09 06:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wiki", "0007_alter_spot_measures"),
    ]

    operations = [
        migrations.AlterField(
            model_name="piece",
            name="skills",
            field=models.ManyToManyField(to="wiki.skill"),
        ),
        migrations.AlterField(
            model_name="spot",
            name="skills",
            field=models.ManyToManyField(to="wiki.skill"),
        ),
    ]
