# Generated by Django 4.2.5 on 2023-09-11 18:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wiki", "0009_book_created_at_book_updated_at_composer_created_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="recording",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="recording",
            name="file",
            field=models.FileField(
                upload_to="recordings",
                validators=[django.core.validators.FileExtensionValidator(["mp3"])],
            ),
        ),
    ]
