# Generated by Django 4.2.5 on 2023-09-12 02:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wiki", "0010_recording_description_alter_recording_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="piece",
            name="external_recording",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="recording",
            name="file",
            field=models.FileField(
                upload_to="recordings/%Y-%m-%d/",
                validators=[django.core.validators.FileExtensionValidator(["mp3"])],
            ),
        ),
    ]
