# Generated by Django 4.2.5 on 2023-09-12 02:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wiki", "0011_piece_external_recording_alter_recording_file"),
    ]

    operations = [
        migrations.RenameField(
            model_name="piece",
            old_name="external_recording",
            new_name="spotify_link",
        ),
        migrations.AddField(
            model_name="piece",
            name="apple_music_link",
            field=models.URLField(blank=True, null=True),
        ),
    ]
