# Generated by Django 4.2.5 on 2023-09-17 23:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wiki", "0014_pieceexercise_nickname_alter_step_spot"),
    ]

    operations = [
        migrations.AlterField(
            model_name="standaloneexercise",
            name="book",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="exercises",
                to="wiki.book",
            ),
        ),
        migrations.AlterField(
            model_name="standaloneexercise",
            name="composer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="standaloneexercises",
                to="wiki.composer",
            ),
        ),
        migrations.AlterField(
            model_name="standaloneexercise",
            name="order",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="standaloneexercise",
            name="recording",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="wiki.recording",
            ),
        ),
    ]
