# Generated by Django 4.2.5 on 2023-09-17 23:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wiki", "0015_alter_standaloneexercise_book_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="standaloneexercise",
            name="book",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="standaloneexercises",
                to="wiki.book",
            ),
        ),
    ]
