# Generated by Django 4.2.5 on 2023-09-19 02:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wiki", "0016_alter_standaloneexercise_book"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pieceexercise",
            name="piece",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="exercises",
                to="wiki.piece",
            ),
        ),
    ]
