# Generated by Django 4.2.5 on 2023-09-19 21:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wiki", "0018_pieceexercise_recording_skill_read_more_link"),
    ]

    operations = [
        migrations.AddField(
            model_name="piece",
            name="amazon_music_link",
            field=models.URLField(blank=True, null=True),
        ),
    ]
