# Generated by Django 4.2.5 on 2023-09-19 21:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wiki", "0020_alter_step_abc_notation"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="link",
            field=models.URLField(blank=True, null=True),
        ),
    ]
