# Generated by Django 4.2.5 on 2023-09-20 17:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wiki", "0021_book_link"),
    ]

    operations = [
        migrations.AlterField(
            model_name="skill",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
