# Generated by Django 4.2.5 on 2023-09-20 18:08

import wiki.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wiki", "0022_alter_skill_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="composer",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="piece",
            name="order",
            field=models.IntegerField(
                blank=True, null=True, validators=[wiki.models.validate_positive]
            ),
        ),
        migrations.AlterField(
            model_name="spot",
            name="order",
            field=models.IntegerField(
                default=999, validators=[wiki.models.validate_positive]
            ),
        ),
        migrations.AlterField(
            model_name="standaloneexercise",
            name="order",
            field=models.IntegerField(
                blank=True, null=True, validators=[wiki.models.validate_positive]
            ),
        ),
    ]
