# Generated by Django 4.2.5 on 2023-09-20 18:08

import wiki.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wiki", "0023_alter_composer_name_alter_piece_order_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="spot",
            name="order",
            field=models.IntegerField(validators=[wiki.models.validate_positive]),
        ),
    ]
