# Generated by Django 4.2.9 on 2024-01-26 00:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wiki", "0026_delete_step"),
    ]

    operations = [
        migrations.AddField(
            model_name="spot",
            name="instructions",
            field=models.TextField(blank=True, null=True),
        ),
    ]
