# Generated by Django 4.2.9 on 2024-12-30 22:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wiki", "0029_piece_goal_tempo"),
    ]

    operations = [
        migrations.CreateModel(
            name="GoLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.CharField(max_length=255)),
                ("url", models.URLField()),
            ],
        ),
    ]
