# Generated by Django 4.2.9 on 2024-12-30 22:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("wiki", "0030_golink"),
    ]

    operations = [
        migrations.DeleteModel(
            name="GoLink",
        ),
    ]
