# Generated by Django 4.2.1 on 2023-06-09 23:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("passkey_auth", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="passkeycredential",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="credentials",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
